name: static_analysis
on:
    pull_request:
    # Run on push, but only if PHP files have changed
    push:
        branches: [ main, develop, feature/pre-new-admin ]
        paths:
            - '**.php'
            - 'composer.json'
            - 'composer.lock'
            - 'phpstan.neon'
            - '.github/workflows/static_analysis.yml'

env:
    GITHUB_ACTIONS_NOTIFY_ON_FAILURE: false

jobs:
    phpstan:
        name: Static Analysis
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.4'

            -   name: Cache Composer dependencies
                uses: actions/cache@v4
                with:
                    path: vendor
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-

            -   name: Install Composer dependencies
                run: COMPOSER_ROOT_VERSION=dev-develop composer install --no-interaction --prefer-dist

            -   name: Run PHPStan
                run: composer analyse
                continue-on-error: true
